---
# COMP90024 2021 Semester 2 Assignment 2
# Group 52
# William Lazarus Kevin Dean 834444 Melbourne, Australia
# Kenneth Huynh 992680 Melbourne, Australia
# Joel Kenna 995401 Melbourne, Australia
# Quinten van der Leest 1135216 Melbourne, Australia
# Walter Zhang 761994 Melbourne, Australia

- name: Create frontend container
  shell: |
    docker build \
    -t front-end \
    --build-arg creds=./configs/credentials1.json \
    -f CCCAssignment2/client/Dockerfile .

- name: Start container
  shell: "docker run -d --network='host' front-end"