---
- name: Create frontend container
  become: yes
  shell: |
    docker build \
    -t front-end \
    --build-arg creds=./configs/credentials1.json \
    -f CCCAssignment2/client/Dockerfile .

- name: Start container
  become: yes
  shell: "docker run -d --network='host' front-end"