---
# COMP90024 2021 Semester 2 Assignment 2
# Group 52
# William Lazarus Kevin Dean 834444 Melbourne, Australia
# Kenneth Huynh 992680 Melbourne, Australia
# Joel Kenna 995401 Melbourne, Australia
# Quinten van der Leest 1135216 Melbourne, Australia
# Walter Zhang 761994 Melbourne, Australia

# Install dependencies on the host
- name: Install pip
  become: yes
  apt:
    name: ['python3-pip']
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
# sudo apt-get update; sudo apt-get install python3-pip

- name: Update pip
  become: yes
  pip:
    name: ['pip']
    state: latest
# pip install --upgrade pip

- name: Pip install Flask
  become: yes
  pip:
    name: ['Flask']
    state: latest

- name: Place config files on host
  copy: 
    src: configs/
    dest: ~/configs/

- name: get credentials files
  find:
    paths: ~/configs/
    patterns: "*.json"
  register: credentials_files

- name: Get MasterIP
  shell: "echo {{ hostvars['localhost']['MasterIP']['openstack_servers'][0]['public_v4']}}"
  register: MasterIP

- name: Populate database user
  lineinfile:
    path: "{{ item.path }}"
    regexp: '^\s*"user": "",'
    state: present
    line: '        "user": "{{ couchdb_user }}",'
  with_items: "{{ credentials_files.files }}"

- name: Populate database pass
  lineinfile:
    path: "{{ item.path }}"
    regexp: '^\s*"pword":'
    state: present
    line: '        "pword": "{{ couchdb_pass }}",'
  with_items: "{{ credentials_files.files }}"

- name: Populate masterIP for uid server
  lineinfile:
    path: "{{ item.path }}"
    regexp: '^\s*"ip": "",'
    state: present
    line: '        "ip": "{{ MasterIP.stdout }}",'
  with_items: "{{ credentials_files.files }}"

- name: get credentials files for user timeline crawlers
  find:
    paths: ~/configs/
    patterns: ["*3.json", "*4.json"]
  register: utc_credentials_files

- name: Get cdb_multi_testIP
  shell: "echo {{ hostvars['localhost']['cdb_multi_testIP']['openstack_servers'][0]['public_v4']}}"
  register: cdb_multi_testIP

- name: Populate cdb_multi_testIP for user timeline crawlers
  lineinfile:
    path: "{{ item.path }}"
    regexp: '^\s*"host": "localhost",'
    state: present
    line: '        "host": "{{ cdb_multi_testIP.stdout }}",'
  with_items: "{{ utc_credentials_files.files }}"

- name: get credentials files for frontend
  find:
    paths: ~/configs/
    patterns: "credentials_api.json"
  register: frontend_credentials_file

- name: Get Slave0IP
  shell: "echo {{ hostvars['localhost']['Slave0IP']['openstack_servers'][0]['public_v4']}}"
  register: Slave0IP

- name: Populate Slave0IP for frontend
  lineinfile:
    path: "{{ item.path }}"
    regexp: '^\s*"ip":'
    state: present
    line: '        "ip": "{{ Slave0IP.stdout }}",'
  with_items: "{{ frontend_credentials_file.files }}"