---

- name: Delete repo if already exists
  file:
    path: "{{ git_repo_location }}"
    state: absent

# Checkout the git repo
- name: Git checkout
  git:
    repo: "https://{{ github_token }}{{ git_repo_https }}"
    dest: "{{ git_repo_location }}"

# - name: debug github repo to clone
#   debug:
#     msg: "https://{{ github_token }}{{ git_repo_https }}"