---
# Install dependencies on the host
- name: Install pip
  become: yes
  apt:
    name: ['python3-pip', 'software-properties-common', 'build-essential']
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Update pip
  pip:
    name: ['pip']
    state: latest