---
# COMP90024 2021 Semester 2 Assignment 2
# Group 52
# William Lazarus Kevin Dean 834444 Melbourne, Australia
# Kenneth Huynh 992680 Melbourne, Australia
# Joel Kenna 995401 Melbourne, Australia
# Quinten van der Leest 1135216 Melbourne, Australia
# Walter Zhang 761994 Melbourne, Australia

#based on: https://mahmudasif.com/atomic/

- name: Check if known_hosts exists
  stat:
      path: "{{ ssh_known_hosts_location }}"
  register: known_hosts_stat

- name: Create known_hosts if it doesn't exist
  file:
      path: "{{ ssh_known_hosts_location }}"
      state: touch
  when: not known_hosts_stat.stat.exists