---
- name: Check if currently running frontend container
  shell: |
    docker ps --all --filter "ancestor=frontend" --quiet
  register: container_exists

- name: Stop previous frontend container
  shell: |
    docker stop $(docker ps --all --filter "ancestor=front-end" --quiet) 
  when: container_exists.stdout_lines|length > 0

- name: Delete previous frontend container
  shell: |
    docker rm $(docker ps --all --filter "ancestor=front-end" --quiet) 
  when: container_exists.stdout_lines|length > 0