---
# COMP90024 2021 Semester 2 Assignment 2
# Group 52
# William Lazarus Kevin Dean 834444 Melbourne, Australia
# Kenneth Huynh 992680 Melbourne, Australia
# Joel Kenna 995401 Melbourne, Australia
# Quinten van der Leest 1135216 Melbourne, Australia
# Walter Zhang 761994 Melbourne, Australia

- name: Check if currently running frontend container
  shell: |
    docker ps --all --filter "ancestor=front-end" --quiet
  register: container_exists

- name: Stop previous frontend container
  shell: |
    docker stop $(docker ps --all --filter "ancestor=front-end" --quiet) 
  when: container_exists.stdout_lines|length > 0

- name: Delete previous frontend container
  shell: |
    docker rm $(docker ps --all --filter "ancestor=front-end" --quiet) 
  when: container_exists.stdout_lines|length > 0