---
# COMP90024 2021 Semester 2 Assignment 2
# Group 52
# William Lazarus Kevin Dean 834444 Melbourne, Australia
# Kenneth Huynh 992680 Melbourne, Australia
# Joel Kenna 995401 Melbourne, Australia
# Quinten van der Leest 1135216 Melbourne, Australia
# Walter Zhang 761994 Melbourne, Australia

- name: get nodes in swarm
  shell: "docker node ls --quiet"
  register: swarm_nodes

- name: get services in swarm
  shell: "docker service ls -q"
  register: results

# - debug:
#     msg: "{{ results }}"

- name: scale to number of nodes in swarm
  shell: "docker service scale {{ item }}={{ swarm_nodes.stdout_lines|length }}"
  loop: "{{ results.stdout_lines }}"

- name: get services in swarm
  shell: "docker service ls -q"
  register: results

# - name: balance across nodes
#   shell: "docker service update --force {{ item }}"
#   loop: "{{ results.stdout_lines }}"