---
# COMP90024 2021 Semester 2 Assignment 2
# Group 52
# William Lazarus Kevin Dean 834444 Melbourne, Australia
# Kenneth Huynh 992680 Melbourne, Australia
# Joel Kenna 995401 Melbourne, Australia
# Quinten van der Leest 1135216 Melbourne, Australia
# Walter Zhang 761994 Melbourne, Australia

#based on: https://mahmudasif.com/atomic/

- name: Check if SSH key already exists
  stat:
      path: "{{ key_location }}"
  register: key_stat_result

- name: Generate SSH key if doesn't already exist
  command: "ssh-keygen -t rsa -f {{ key_location }} -N ''"
  when: not key_stat_result.stat.exists

# - name: Add SSH key to SSH agent
#   shell: "ssh-add {{ private_key_location }}"
