---
#get IPs of all OS VMs
- name: Get OS instances
  os_server_info:
  register: os_instances_result
  
- name: Save OS instances for other roles
  set_fact:
    os_instances_fact: "{{ os_instances_result }}" 

- name: Save Master instance IP
  os_server_info:
    server: Master
  register: MasterIP

# - name: Save Master instance IP
#   shell: "echo {{ item.public_v4 }}"
#   loop: "{{ os_instances_result.openstack_servers }}"
#   when: item.name == 'Master'
#   register: output

# - name: Continue saving MasterIP
  
#   with_items: "{{  }}"

- name: debug
  debug: 
    msg: "{{ MasterIP }}"

- name: Show instances
  debug:
    msg: "Image name: {{ item.name }}; Image id: {{ item.id }}"
  loop: "{{ os_instances_result.openstack_servers }}"

- name: Make OS instance IPs hosts
  add_host:
    name: "{{ item.public_v4 }}"
    group: VMs
  loop: "{{ os_instances_result.openstack_servers }}"