#!/usr/bin/bash
./make_vms.sh
./clone_gits.sh
./setup_docker.sh
./initialise_database.sh
./load_view.sh
./initialise_harvesters.sh
./initialise_tweet_analysis.sh
./initialise_frontend.sh
./initialise_frontend_api.sh
