---
- name: Create frontend api container
  become: yes
  shell: |
    docker build \
    -t front-end-api \
    --build-arg creds=./configs/credentials1.json \
    -f CCCAssignment2/db_api/Dockerfile .

- name: Start container
  become: yes
  shell: "docker run -d --network='host' front-end-api"